### ISSUE TITLE
Serpo's Console crashes when opening the mod menu.

### ISSUE THREAD

**Issue by MonadoArt** [omo50/Serpos-Console#1]
Serpo's Console crashes when opening the mod menu and libIPN is enabled 
It works fine when libIPN is disabled

Crash report: https://paste.ee/p/6cpcr
Log: https://paste.ee/p/DTJew

**Comment by omo50** [comment]
looking into a fix now. will leave updates in this thread

**Comment by omo50** [comment]
Fixed in SC 1.6 beta 1
